### ISSUE TITLE
Severity: 8192  Message: Methods with the same name as their class will not be constructors in a future version of PHP; Template has a deprecated constructor

### ISSUE THREAD

**Issue by natsirasrafi** [ajhoel43/ci-with-gentelella#1]
Severity: 8192

Message: Methods with the same name as their class will not be constructors in a future version of PHP; Template has a deprecated constructor

**Comment by ajhoel43** [comment]
http://php.net/manual/en/migration70.deprecated.php

just change constructor function name to __construct() in Template.php
